version: "3.8"

services:

  configserver:
    image: iamsiddiquek/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - irisbank
     
     
  eurekaserver:
    image: iamsiddiquek/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - irisbank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/     
      
  accounts:
    image: iamsiddiquek/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - irisbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      
      
  accounts1:
    image: iamsiddiquek/accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8080"
    networks:
      - irisbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka


  
  loans:
    image: iamsiddiquek/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - irisbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      
  cards:
    image: iamsiddiquek/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - irisbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      


  gatewayserver:
    image: iamsiddiquek/iris-gateway:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - irisbank
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/



      
networks:
  irisbank: